# The synthetic sample datasets in inst/extdata/sample-data/, generated by
# data-raw/make_sample_data.R.

sample_file <- function(name, ext) {
  app_sys("extdata", "sample-data", paste0(name, ".", ext))
}

sample_data <- function(name, ext) read_uploaded_data(sample_file(name, ext))

sample_names <- c(
  "adsl_sample", "adae_sample", "adsl_sample_v2", "edge_cases",
  "adsl_sample_copy", "adae_sample_v2", "adsl_sample_rounded",
  "adsl_sample_sorted"
)

test_that("every sample dataset ships as both CSV and XPT, with a README", {
  for (name in sample_names) {
    for (ext in c("csv", "xpt")) {
      path <- sample_file(name, ext)
      expect_true(nzchar(path) && file.exists(path), info = paste(name, ext))
    }
  }
  expect_true(file.exists(app_sys("extdata", "sample-data", "README.md")))
})

test_that("every sample file loads through read_uploaded_data()", {
  for (name in sample_names) {
    csv <- sample_data(name, "csv")
    xpt <- sample_data(name, "xpt")

    expect_gt(nrow(csv$data), 0)
    expect_identical(nrow(csv$data), nrow(xpt$data), info = name)
    expect_identical(names(csv$data), names(xpt$data), info = name)
    # XPT carries variable labels, CSV does not
    expect_true(all(nzchar(xpt$meta$label)), info = name)
    expect_false(any(nzchar(csv$meta$label)), info = name)
  }
})

test_that("adsl_sample has about 60 subjects, dates and some missing values", {
  for (ext in c("csv", "xpt")) {
    adsl <- sample_data("adsl_sample", ext)$data

    expect_identical(nrow(adsl), 60L)
    expect_identical(anyDuplicated(adsl$USUBJID), 0L)
    expect_true(all(c(
      "USUBJID", "STUDYID", "SITEID", "ARM", "SEX", "RACE", "AGE", "AGEGR1",
      "WEIGHTBL", "HEIGHTBL", "BMIBL", "TRTSDT", "TRTEDT", "SAFFL", "DTHFL"
    ) %in% names(adsl)))
    expect_s3_class(adsl$TRTSDT, "Date")
    expect_s3_class(adsl$TRTEDT, "Date")
    expect_true(anyNA(adsl$WEIGHTBL))
    expect_true(any(adsl$DTHFL == "") && any(adsl$DTHFL == "Y"))
  }
})

test_that("adae_sample is linked to adsl_sample by USUBJID", {
  adsl <- sample_data("adsl_sample", "xpt")$data
  adae <- sample_data("adae_sample", "xpt")$data

  expect_true(all(c(
    "AETERM", "AEDECOD", "AEBODSYS", "AESEV", "AESER", "AEREL", "ASTDT",
    "AENDT", "AEDUR"
  ) %in% names(adae)))
  expect_true(all(adae$USUBJID %in% adsl$USUBJID))
  expect_gt(length(unique(adae$USUBJID)), 30L)
  expect_true(anyNA(adae$AENDT)) # ongoing events
})

test_that("adsl_sample_v2 differs from adsl_sample in every intended way", {
  for (ext in c("csv", "xpt")) {
    base <- sample_data("adsl_sample", ext)$data
    v2 <- sample_data("adsl_sample_v2", ext)$data

    res <- compare_datasets(base, v2)

    expect_false(res$identical, info = ext)
    issues <- res$table
    expect_true(all(c(
      "value_difference", "column_only_in_base", "column_only_in_compare",
      "type_mismatch", "row_count", "rows_only_in_base"
    ) %in% issues$issue), info = ext)
    expect_identical(issues$variable[issues$issue == "column_only_in_base"], "HEIGHTBL")
    expect_identical(issues$variable[issues$issue == "column_only_in_compare"], "RANDFL")
    expect_identical(issues$variable[issues$issue == "type_mismatch"], "WEIGHTBL")
    expect_true(all(c("AGE", "ARM", "RACE") %in%
                      issues$variable[issues$issue == "value_difference"]))
  }
})

test_that("the extra Compare pairs give the differences they are meant to", {
  issues_of <- function(base, other, ext) {
    compare_datasets(sample_data(base, ext)$data, sample_data(other, ext)$data)
  }

  for (ext in c("csv", "xpt")) {
    # an unchanged copy
    expect_true(issues_of("adsl_sample", "adsl_sample_copy", ext)$identical, info = ext)

    # modified ADAE: values, a renamed column and extra rows
    ae <- issues_of("adae_sample", "adae_sample_v2", ext)
    expect_false(ae$identical)
    expect_identical(ae$table$variable[ae$table$issue == "column_only_in_base"], "AEREL")
    expect_identical(ae$table$variable[ae$table$issue == "column_only_in_compare"], "AERELAT")
    expect_true("rows_only_in_compare" %in% ae$table$issue)
    expect_setequal(
      ae$table$variable[ae$table$issue == "value_difference"],
      c("AESEV", "AEDUR", "AETERM")
    )

    # rounding is reported, noise below diffdf's tolerance is not
    rnd <- issues_of("adsl_sample", "adsl_sample_rounded", ext)$table
    expect_setequal(rnd$variable[rnd$issue == "value_difference"], c("WEIGHTBL", "BMIBL"))
    expect_false("HEIGHTBL" %in% rnd$variable)
    expect_false("type_mismatch" %in% rnd$issue)

    # same content, different order: rows are compared by position
    srt <- issues_of("adsl_sample", "adsl_sample_sorted", ext)$table
    expect_true(all(srt$issue == "value_difference"))
    expect_true(all(c("USUBJID", "AGE", "ARM") %in% srt$variable))
    expect_false(any(c("column_only_in_base", "column_only_in_compare",
                       "row_count") %in% srt$issue))
  }
})

test_that("the sorted copy holds the same subjects as adsl_sample", {
  base <- sample_data("adsl_sample", "csv")$data
  srt <- sample_data("adsl_sample_sorted", "csv")$data
  expect_identical(nrow(srt), nrow(base))
  expect_setequal(srt$USUBJID, base$USUBJID)
  expect_identical(names(srt), rev(names(base)))
  expect_false(is.unsorted(srt$AGE))
})

test_that("adsl_sample compared with itself is identical", {
  adsl <- sample_data("adsl_sample", "csv")$data
  expect_true(compare_datasets(adsl, adsl)$identical)
})

test_that("edge_cases contains each awkward kind of column", {
  for (ext in c("csv", "xpt")) {
    edge <- sample_data("edge_cases", ext)$data

    expect_true(all(is.na(edge$ALLMISS)), info = ext)
    expect_true(any(edge$EMPTYSTR == "") && any(edge$EMPTYSTR != ""), info = ext)
    expect_identical(length(unique(edge$CONSTANT)), 1L)
    expect_identical(length(unique(edge$ID)), nrow(edge)) # high cardinality
    expect_true(any(edge$NEGVAL < 0))
    expect_gt(max(nchar(edge$LONGTXT)), 150L)
    expect_s3_class(edge$EVENTDT, "Date")
    expect_true(anyNA(edge$EVENTDT))
  }
})

test_that("edge_cases go through the summaries and charts without error", {
  edge <- sample_data("edge_cases", "xpt")
  summary <- expect_no_error(summarize_data(edge$data))
  expect_named(summary, c("numeric", "categorical", "date"))

  choices <- chart_choices(edge$data, edge$meta)
  # the ID and free-text columns are not offered; the all-missing one is not
  # numeric-chartable
  expect_identical(unname(choices$numeric), "NEGVAL")
  expect_identical(unname(choices$categorical), c("EMPTYSTR", "CONSTANT"))
  expect_no_error(plot_missing(edge$data))
  expect_no_error(plot_histogram(edge$data, "ALLMISS"))
  expect_no_error(plot_composition(edge$data, "CONSTANT"))
  expect_no_error(plot_boxplot(edge$data, "NEGVAL", "EMPTYSTR"))
})
